[04:15:17] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [server.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [server.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/item/EntityItem
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ng.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1454) ~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.item.EntityItem
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ng.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1454) ~[MinecraftServer.class:?]
        ... 12 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.creativemd.itemphysic.ItemTransformer@470d183 from coremod ItemPatchingLoader
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[server.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ng.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1454) ~[MinecraftServer.class:?]
        ... 12 more
Caused by: java.lang.NullPointerException
        at com.creativemd.itemphysic.ItemTransformer$3.transform(ItemTransformer.java:156) ~[ItemTransformer$3.class:?]
        at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:43) ~[CreativeTransformer.class:?]
        at com.creativemd.creativecore.transformer.CreativeTransformer.transform(CreativeTransformer.java:32) ~[CreativeTransformer.class:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[server.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:497) ~[ng.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1454) ~[MinecraftServer.class:?]
        ... 12 more
[04:15:17] [main/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[04:15:17] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:15:17] [main/INFO]: [STDERR]:       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[04:15:17] [main/INFO]: [STDERR]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[04:15:17] [main/INFO]: [STDERR]:       at java.lang.reflect.Method.invoke(Unknown Source)
[04:15:17] [main/INFO]: [STDERR]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
[04:15:17] [main/INFO]: [STDERR]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
[04:15:17] [main/INFO]: [STDERR]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[04:15:17] [main/INFO]: [STDERR]:       at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[04:15:17] [main/INFO]: [STDERR]:       at java.lang.SecurityManager.checkExit(Unknown Source)
[04:15:17] [main/INFO]: [STDERR]:       at java.lang.Runtime.exit(Unknown Source)
[04:15:17] [main/INFO]: [STDERR]:       at java.lang.System.exit(Unknown Source)
[04:15:17] [main/INFO]: [STDERR]:       at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[04:15:17] [main/INFO]: [STDERR]:       at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[04:15:17] [main/INFO]: [STDERR]:       ... 6 more
Press any key to continue . . .
